DELETE FROM footer_legal_links WHERE url IN ('/impressum','/datenschutz','/agb','/widerruf','/cookies');

DELETE FROM _pages_v_blocks_content_columns WHERE _parent_id IN (SELECT c.id FROM _pages_v_blocks_content c JOIN _pages_v v ON v.id = c._parent_id WHERE v.version_slug IN ('impressum','datenschutz','agb','widerruf','cookies'));

DELETE FROM _pages_v_blocks_content WHERE _parent_id IN (SELECT id FROM _pages_v WHERE version_slug IN ('impressum','datenschutz','agb','widerruf','cookies'));

DELETE FROM _pages_v WHERE version_slug IN ('impressum','datenschutz','agb','widerruf','cookies');

DELETE FROM pages_blocks_content_columns WHERE _parent_id IN (SELECT id FROM pages_blocks_content WHERE _parent_id IN (SELECT id FROM pages WHERE slug IN ('impressum','datenschutz','agb','widerruf','cookies')));

DELETE FROM pages_blocks_content WHERE _parent_id IN (SELECT id FROM pages WHERE slug IN ('impressum','datenschutz','agb','widerruf','cookies'));

DELETE FROM pages WHERE slug IN ('impressum','datenschutz','agb','widerruf','cookies');

INSERT INTO pages (id, title, published_on, hero_type, hero_rich_text, meta_title, meta_description, generate_slug, slug, updated_at, created_at, _status)
VALUES (10, 'Impressum', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Impressum", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Impressum', 'Impressum und Anbieterkennzeichnung von Nabea.', false, 'impressum', NOW(), NOW(), 'published');

INSERT INTO pages_blocks_content (_order, _parent_id, _path, id, block_name)
VALUES (1, 10, 'layout', 'legal_content_impressum', NULL);

INSERT INTO pages_blocks_content_columns (_order, _parent_id, id, size, rich_text, enable_link)
VALUES (1, 'legal_content_impressum', 'legal_col_impressum', 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Angaben gem\u00e4\u00df \u00a7 5 ECG / \u00a7 25 MedienG. Bitte ersetze diesen Platzhaltertext durch die vollst\u00e4ndigen Impressumsangaben (Firma, Adresse, Kontakt, UID, etc.).", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Firmenname: [Firmenname eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Adresse: [Stra\u00dfe, PLZ Ort, \u00d6sterreich]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "E-Mail: hello@nabea.at", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Telefon: [Telefonnummer eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "UID-Nummer: [UID eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Gesch\u00e4ftsf\u00fchrung: [Name eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite dient als Platzhalter und muss vor dem Livegang rechtlich gepr\u00fcft und vervollst\u00e4ndigt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false);

INSERT INTO pages (id, title, published_on, hero_type, hero_rich_text, meta_title, meta_description, generate_slug, slug, updated_at, created_at, _status)
VALUES (11, 'Datenschutzerklärung', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Datenschutzerkl\u00e4rung", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Datenschutzerklärung', 'Informationen zur Verarbeitung personenbezogener Daten bei Nabea.', false, 'datenschutz', NOW(), NOW(), 'published');

INSERT INTO pages_blocks_content (_order, _parent_id, _path, id, block_name)
VALUES (1, 11, 'layout', 'legal_content_datenschutz', NULL);

INSERT INTO pages_blocks_content_columns (_order, _parent_id, id, size, rich_text, enable_link)
VALUES (1, 'legal_content_datenschutz', 'legal_col_datenschutz', 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Datenschutzerkl\u00e4rung (DSGVO). Ersetze diesen Text durch eine vollst\u00e4ndige, rechtskonforme Datenschutzerkl\u00e4rung.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Wir verarbeiten personenbezogene Daten nur im Rahmen der gesetzlichen Vorgaben.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Zu den typischen Verarbeitungszwecken geh\u00f6ren Bestellabwicklung, Kundenkonto, Newsletter und Website-Analyse.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Bitte erg\u00e4nze Angaben zu Verantwortlichem, Rechtsgrundlagen, Speicherdauer, Empf\u00e4ngern, Cookies, Betroffenenrechten und Kontakt f\u00fcr Datenschutzanfragen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false);

INSERT INTO pages (id, title, published_on, hero_type, hero_rich_text, meta_title, meta_description, generate_slug, slug, updated_at, created_at, _status)
VALUES (12, 'AGB', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "AGB", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'AGB', 'Allgemeine Geschäftsbedingungen von Nabea.', false, 'agb', NOW(), NOW(), 'published');

INSERT INTO pages_blocks_content (_order, _parent_id, _path, id, block_name)
VALUES (1, 12, 'layout', 'legal_content_agb', NULL);

INSERT INTO pages_blocks_content_columns (_order, _parent_id, id, size, rich_text, enable_link)
VALUES (1, 'legal_content_agb', 'legal_col_agb', 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Allgemeinen Gesch\u00e4ftsbedingungen. Ersetze diesen Text durch deine verbindlichen AGB.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Geltungsbereich: Diese AGB gelten f\u00fcr alle Bestellungen \u00fcber unseren Online-Shop.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Vertragsschluss: Mit Abschluss der Bestellung kommt ein Kaufvertrag zustande.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Preise und Zahlung: Alle Preise verstehen sich in Euro inkl. gesetzlicher MwSt., sofern nicht anders angegeben.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Lieferung: Versand erfolgt gem\u00e4\u00df den auf der Website angegebenen Lieferbedingungen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false);

INSERT INTO pages (id, title, published_on, hero_type, hero_rich_text, meta_title, meta_description, generate_slug, slug, updated_at, created_at, _status)
VALUES (13, 'Widerrufsbelehrung', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Widerrufsbelehrung", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Widerrufsbelehrung', 'Informationen zum Widerrufsrecht bei Nabea.', false, 'widerruf', NOW(), NOW(), 'published');

INSERT INTO pages_blocks_content (_order, _parent_id, _path, id, block_name)
VALUES (1, 13, 'layout', 'legal_content_widerruf', NULL);

INSERT INTO pages_blocks_content_columns (_order, _parent_id, id, size, rich_text, enable_link)
VALUES (1, 'legal_content_widerruf', 'legal_col_widerruf', 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Widerrufsbelehrung und das Widerrufsformular. Ersetze diesen Text durch den gesetzlich vorgeschriebenen Text.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Verbraucherinnen und Verbraucher haben bei Fernabsatzvertr\u00e4gen grunds\u00e4tzlich ein 14-t\u00e4giges Widerrufsrecht.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Bitte erg\u00e4nze hier die vollst\u00e4ndige Widerrufsbelehrung inkl. Frist, Folgen des Widerrufs und ggf. Ausnahmen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "F\u00fcge au\u00dferdem ein Muster-Widerrufsformular hinzu.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false);

INSERT INTO pages (id, title, published_on, hero_type, hero_rich_text, meta_title, meta_description, generate_slug, slug, updated_at, created_at, _status)
VALUES (14, 'Cookie-Richtlinie', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Cookie-Richtlinie", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Cookie-Richtlinie', 'Informationen zur Verwendung von Cookies auf der Nabea-Website.', false, 'cookies', NOW(), NOW(), 'published');

INSERT INTO pages_blocks_content (_order, _parent_id, _path, id, block_name)
VALUES (1, 14, 'layout', 'legal_content_cookies', NULL);

INSERT INTO pages_blocks_content_columns (_order, _parent_id, id, size, rich_text, enable_link)
VALUES (1, 'legal_content_cookies', 'legal_col_cookies', 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Cookie-Richtlinie. Ersetze diesen Text durch eine vollst\u00e4ndige \u00dcbersicht der eingesetzten Cookies.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Wir verwenden Cookies und \u00e4hnliche Technologien, um die Website zu betreiben und ggf. Nutzungsstatistiken zu erstellen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Bitte liste hier notwendige Cookies, Statistik-/Marketing-Cookies, Anbieter, Speicherdauer und Opt-in/Opt-out-M\u00f6glichkeiten auf.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Verweise ggf. auf die Datenschutzerkl\u00e4rung und das Cookie-Banner.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false);

INSERT INTO _pages_v (id, parent_id, version_title, version_published_on, version_hero_type, version_hero_rich_text, version_meta_title, version_meta_description, version_generate_slug, version_slug, version_updated_at, version_created_at, version__status, created_at, updated_at, latest, autosave)
VALUES (100, 10, 'Impressum', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Impressum", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Impressum', 'Impressum und Anbieterkennzeichnung von Nabea.', false, 'impressum', NOW(), NOW(), 'published', NOW(), NOW(), true, false);

INSERT INTO _pages_v_blocks_content (_order, _parent_id, _path, _uuid, block_name)
VALUES (1, 100, 'layout', 'legal_v_content_impressum', NULL)
RETURNING id;

INSERT INTO _pages_v_blocks_content_columns (_order, _parent_id, size, rich_text, enable_link, _uuid)
SELECT 1, c.id, 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Angaben gem\u00e4\u00df \u00a7 5 ECG / \u00a7 25 MedienG. Bitte ersetze diesen Platzhaltertext durch die vollst\u00e4ndigen Impressumsangaben (Firma, Adresse, Kontakt, UID, etc.).", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Firmenname: [Firmenname eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Adresse: [Stra\u00dfe, PLZ Ort, \u00d6sterreich]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "E-Mail: hello@nabea.at", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Telefon: [Telefonnummer eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "UID-Nummer: [UID eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Gesch\u00e4ftsf\u00fchrung: [Name eintragen]", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite dient als Platzhalter und muss vor dem Livegang rechtlich gepr\u00fcft und vervollst\u00e4ndigt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false, 'legal_v_col_impressum'
FROM _pages_v_blocks_content c
WHERE c._parent_id = 100 AND c._uuid = 'legal_v_content_impressum';

INSERT INTO _pages_v (id, parent_id, version_title, version_published_on, version_hero_type, version_hero_rich_text, version_meta_title, version_meta_description, version_generate_slug, version_slug, version_updated_at, version_created_at, version__status, created_at, updated_at, latest, autosave)
VALUES (101, 11, 'Datenschutzerklärung', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Datenschutzerkl\u00e4rung", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Datenschutzerklärung', 'Informationen zur Verarbeitung personenbezogener Daten bei Nabea.', false, 'datenschutz', NOW(), NOW(), 'published', NOW(), NOW(), true, false);

INSERT INTO _pages_v_blocks_content (_order, _parent_id, _path, _uuid, block_name)
VALUES (1, 101, 'layout', 'legal_v_content_datenschutz', NULL)
RETURNING id;

INSERT INTO _pages_v_blocks_content_columns (_order, _parent_id, size, rich_text, enable_link, _uuid)
SELECT 1, c.id, 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Datenschutzerkl\u00e4rung (DSGVO). Ersetze diesen Text durch eine vollst\u00e4ndige, rechtskonforme Datenschutzerkl\u00e4rung.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Wir verarbeiten personenbezogene Daten nur im Rahmen der gesetzlichen Vorgaben.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Zu den typischen Verarbeitungszwecken geh\u00f6ren Bestellabwicklung, Kundenkonto, Newsletter und Website-Analyse.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Bitte erg\u00e4nze Angaben zu Verantwortlichem, Rechtsgrundlagen, Speicherdauer, Empf\u00e4ngern, Cookies, Betroffenenrechten und Kontakt f\u00fcr Datenschutzanfragen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false, 'legal_v_col_datenschutz'
FROM _pages_v_blocks_content c
WHERE c._parent_id = 101 AND c._uuid = 'legal_v_content_datenschutz';

INSERT INTO _pages_v (id, parent_id, version_title, version_published_on, version_hero_type, version_hero_rich_text, version_meta_title, version_meta_description, version_generate_slug, version_slug, version_updated_at, version_created_at, version__status, created_at, updated_at, latest, autosave)
VALUES (102, 12, 'AGB', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "AGB", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'AGB', 'Allgemeine Geschäftsbedingungen von Nabea.', false, 'agb', NOW(), NOW(), 'published', NOW(), NOW(), true, false);

INSERT INTO _pages_v_blocks_content (_order, _parent_id, _path, _uuid, block_name)
VALUES (1, 102, 'layout', 'legal_v_content_agb', NULL)
RETURNING id;

INSERT INTO _pages_v_blocks_content_columns (_order, _parent_id, size, rich_text, enable_link, _uuid)
SELECT 1, c.id, 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Allgemeinen Gesch\u00e4ftsbedingungen. Ersetze diesen Text durch deine verbindlichen AGB.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Geltungsbereich: Diese AGB gelten f\u00fcr alle Bestellungen \u00fcber unseren Online-Shop.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Vertragsschluss: Mit Abschluss der Bestellung kommt ein Kaufvertrag zustande.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Preise und Zahlung: Alle Preise verstehen sich in Euro inkl. gesetzlicher MwSt., sofern nicht anders angegeben.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Lieferung: Versand erfolgt gem\u00e4\u00df den auf der Website angegebenen Lieferbedingungen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false, 'legal_v_col_agb'
FROM _pages_v_blocks_content c
WHERE c._parent_id = 102 AND c._uuid = 'legal_v_content_agb';

INSERT INTO _pages_v (id, parent_id, version_title, version_published_on, version_hero_type, version_hero_rich_text, version_meta_title, version_meta_description, version_generate_slug, version_slug, version_updated_at, version_created_at, version__status, created_at, updated_at, latest, autosave)
VALUES (103, 13, 'Widerrufsbelehrung', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Widerrufsbelehrung", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Widerrufsbelehrung', 'Informationen zum Widerrufsrecht bei Nabea.', false, 'widerruf', NOW(), NOW(), 'published', NOW(), NOW(), true, false);

INSERT INTO _pages_v_blocks_content (_order, _parent_id, _path, _uuid, block_name)
VALUES (1, 103, 'layout', 'legal_v_content_widerruf', NULL)
RETURNING id;

INSERT INTO _pages_v_blocks_content_columns (_order, _parent_id, size, rich_text, enable_link, _uuid)
SELECT 1, c.id, 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Widerrufsbelehrung und das Widerrufsformular. Ersetze diesen Text durch den gesetzlich vorgeschriebenen Text.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Verbraucherinnen und Verbraucher haben bei Fernabsatzvertr\u00e4gen grunds\u00e4tzlich ein 14-t\u00e4giges Widerrufsrecht.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Bitte erg\u00e4nze hier die vollst\u00e4ndige Widerrufsbelehrung inkl. Frist, Folgen des Widerrufs und ggf. Ausnahmen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "F\u00fcge au\u00dferdem ein Muster-Widerrufsformular hinzu.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false, 'legal_v_col_widerruf'
FROM _pages_v_blocks_content c
WHERE c._parent_id = 103 AND c._uuid = 'legal_v_content_widerruf';

INSERT INTO _pages_v (id, parent_id, version_title, version_published_on, version_hero_type, version_hero_rich_text, version_meta_title, version_meta_description, version_generate_slug, version_slug, version_updated_at, version_created_at, version__status, created_at, updated_at, latest, autosave)
VALUES (104, 14, 'Cookie-Richtlinie', NOW(), 'lowImpact', '{"root": {"type": "root", "children": [{"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Cookie-Richtlinie", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h1", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, 'Cookie-Richtlinie', 'Informationen zur Verwendung von Cookies auf der Nabea-Website.', false, 'cookies', NOW(), NOW(), 'published', NOW(), NOW(), true, false);

INSERT INTO _pages_v_blocks_content (_order, _parent_id, _path, _uuid, block_name)
VALUES (1, 104, 'layout', 'legal_v_content_cookies', NULL)
RETURNING id;

INSERT INTO _pages_v_blocks_content_columns (_order, _parent_id, size, rich_text, enable_link, _uuid)
SELECT 1, c.id, 'full', '{"root": {"type": "root", "children": [{"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Platzhalter f\u00fcr die Cookie-Richtlinie. Ersetze diesen Text durch eine vollst\u00e4ndige \u00dcbersicht der eingesetzten Cookies.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "heading", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Inhalt", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "tag": "h2", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Wir verwenden Cookies und \u00e4hnliche Technologien, um die Website zu betreiben und ggf. Nutzungsstatistiken zu erstellen.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Bitte liste hier notwendige Cookies, Statistik-/Marketing-Cookies, Anbieter, Speicherdauer und Opt-in/Opt-out-M\u00f6glichkeiten auf.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Verweise ggf. auf die Datenschutzerkl\u00e4rung und das Cookie-Banner.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}, {"type": "paragraph", "children": [{"type": "text", "detail": 0, "format": 0, "mode": "normal", "style": "", "text": "Diese Seite ist ein Platzhalter und muss vor dem Livegang durch gepr\u00fcften Rechtstext ersetzt werden.", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "textFormat": 0, "textStyle": "", "version": 1}], "direction": "ltr", "format": "", "indent": 0, "version": 1}}'::jsonb, false, 'legal_v_col_cookies'
FROM _pages_v_blocks_content c
WHERE c._parent_id = 104 AND c._uuid = 'legal_v_content_cookies';

INSERT INTO footer_legal_links (_order, _parent_id, id, label, url)
VALUES (1, 1, 'legal_link_1', 'Impressum', '/impressum');

INSERT INTO footer_legal_links (_order, _parent_id, id, label, url)
VALUES (2, 1, 'legal_link_2', 'Datenschutz', '/datenschutz');

INSERT INTO footer_legal_links (_order, _parent_id, id, label, url)
VALUES (3, 1, 'legal_link_3', 'AGB', '/agb');

INSERT INTO footer_legal_links (_order, _parent_id, id, label, url)
VALUES (4, 1, 'legal_link_4', 'Widerruf', '/widerruf');

INSERT INTO footer_legal_links (_order, _parent_id, id, label, url)
VALUES (5, 1, 'legal_link_5', 'Cookies', '/cookies');

SELECT setval(pg_get_serial_sequence('pages','id'), GREATEST((SELECT MAX(id) FROM pages), 1));

SELECT setval(pg_get_serial_sequence('_pages_v','id'), GREATEST((SELECT MAX(id) FROM _pages_v), 1));
